# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Dev version
      uses: codaline-io/dev-version-action@0.1.2
    - run: npm pack
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: npm-package
        path: wc-react-*.tgz
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
